ren Unary_Common.exe Unary_CommonDebug.exe
move Unary_Common_data Unary_CommonDebug_data
ren Unary_Common.pck Unary_CommonDebug.pck
Unary_CommonDebug.exe
ren Unary_CommonDebug.exe Unary_Common.exe
move Unary_CommonDebug_data Unary_Common_data
ren Unary_CommonDebug.pck Unary_Common.pck